require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb
