require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/migrate/20230818163315_create_password_reset_tokens.rb
    - db/migrate/20230818163316_create_email_verification_tokens.rb

Metrics/BlockLength:
  Exclude:
    - config/environments/development.rb

Metrics/AbcSize:
  Exclude:
    - app/controllers/sessions_controller.rb
