plugins:
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rails

AllCops:
  NewCops: enable

Lint/MissingSuper:
  Enabled: false

Style/Documentation:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Exclude:
    - db/migrate/20230818163315_create_password_reset_tokens.rb
    - db/migrate/20230818163316_create_email_verification_tokens.rb
    - db/migrate/20230817173059_create_active_storage_tables.active_storage.rb

Metrics:
  Enabled: false
