databases:
  - name: musiccoop
    region: oregon
    databaseName: musiccoop
    user: musiccoop

services:
  - type: web
    name: musiccoop
    region: oregon
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: musiccoop
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: sidekiq-redis
    region: oregon
    maxmemoryPolicy: noeviction
    ipAllowList: [] # only allow internal connections
  - type: worker
    name: sidekiq-worker
    runtime: ruby
    region: oregon
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
