default: &default
development:
  secret_key: <%= ENV.fetch('STRIPE_SECRET_KEY', 'stripe-secret-key' ) %>
  endpoint_secret: <%= ENV.fetch('STRIPE_ENDPOINT_SECRET', 'stripe-secret-key') %>
test:
  secret_key:
  endpoint_secret:
production:
  secret_key: <%= ENV.fetch('STRIPE_SECRET_KEY') %>
  endpoint_secret: <%= ENV.fetch('STRIPE_ENDPOINT_SECRET') %>
