# frozen_string_literal: true

module PayoutDetailsHelper
  def options_for_payout_details_country_select
    [['🇦🇷 Argentina (ARS)', 'argentina'],
     ['🇦🇺 Australia (AUD)', 'australia'],
     ['🇧🇩 Bangladesh (BDT)', 'bangladesh'],
     ['🇧🇷 Brazil (BRL)', 'brazil'],
     ['🇧🇬 Bulgaria (BGN)', 'bulgaria'],
     ['🇨🇦 Canada (CAD)', 'canada'],
     ['🇨🇱 Chile (CLP)', 'chile'],
     ['🇨🇳 China (CNY)', 'china'],
     ['🇨🇴 Colombia (COP)', 'colombia'],
     ['🇨🇷 Costa Rica (CRC)', 'costa_rica'],
     ['🇨🇿 Czech Republic (CZK)', 'czech_republic'],
     ['🇩🇰 Denmark (DKK)', 'denmark'],
     ['🇪🇬 Egypt (EGP)', 'egypt'],
     ['🇪🇺 Europe (EUR)', 'europe'],
     ['🇬🇪 Georgia (GEL)', 'georgia'],
     ['🇬🇹 Guatemala (GTQ)', 'guatemala'],
     ['🇬🇭 Ghana (GHS)', 'ghana'],
     ['🇭🇰 Hong Kong (HKD)', 'hong_kong'],
     ['🇭🇺 Hungary (HUF)', 'hungary'],
     ['🇮🇩 Indonesia (IDR)', 'indonesia'],
     ['🇮🇱 Israel (ILS)', 'israel'],
     ['🇯🇵 Japan (JPY)', 'japan'],
     ['🇰🇪 Kenya (KES)', 'kenya'],
     ['🇲🇾 Malaysia (MYR)', 'malaysia'],
     ['🇲🇽 Mexico (MXN)', 'mexico'],
     ['🇲🇦 Morocco (MAD)', 'morocco'],
     ['🇳🇵 Nepal (NPR)', 'nepal'],
     ['🇳🇿 New Zealand (NZD)', 'new_zealand'],
     ['🇳🇴 Norway (NOK)', 'norway'],
     ['🇵🇰 Pakistan (PKR)', 'pakistan'],
     ['🇵🇭 Philippines (PHP)', 'philippines'],
     ['🇵🇱 Poland (PLN)', 'poland'],
     ['🇷🇴 Romania (RON)', 'romania'],
     ['🇸🇬 Singapore (SGD)', 'singapore'],
     ['🇿🇦 South Africa (ZAR)', 'south_africa'],
     ['🇰🇷 South Korea (KRW)', 'south_korea'],
     ['🇱🇰 Sri Lanka (LKR)', 'sri_lanka'],
     ['🇸🇪 Sweden (SEK)', 'sweden'],
     ['🇨🇭 Switzerland and Liechtenstein (CHF)', 'switzerland_and_liechtenstein'],
     ['🇹🇿 Tanzania (TZS)', 'tanzania'],
     ['🇹🇭 Thailand (THB)', 'thailand'],
     ['🇹🇷 Turkey (TRY)', 'turkey'],
     ['🇺🇬 Uganda (UGX)', 'uganda'],
     ['🇺🇦 Ukraine (UAH)', 'ukraine'],
     ['🇦🇪 United Arab Emirates (AED)', 'united_arab_emirates'],
     ['🇬🇧 United Kingdom (GBP)', 'united_kingdom'],
     ['🇺🇸 United States of America (USD)', 'united_states_of_america'],
     ['🇺🇾 Uruguay (UYU)', 'uruguay'],
     ['🇻🇳 Vietnam (VND)', 'vietnam'],
     ['🇿🇲 Zambia (ZMW)', 'zambia']]
  end
end
